FROM ruby:2.6.2
MAINTAINER Henrique Feitosa <hfeitosa@grupoea.com.br>

RUN apt-get update -qq && apt-get install -y build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
RUN gem install bundler
ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME

RUN $APP_HOME/ruby app.rb
